
title: Apoorv Mishra
logo: /assets/profile_pic_linkedin_apoorv.jpg   
description: AI Product Manager | Building Intelligent Systems for Business Growth
show_downloads: false
theme: jekyll-theme-minimal
